name: Build 🏗️ Servers ️💁
on:
  push:
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-host:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    strategy:
      matrix:
        host:
          - revan
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.host }} 🐧
      run: |
        # Disable non-redist packages
        for NON_REDIST in cider pico8; do
          if [ -d "pkgs/${NON_REDIST}" ]; then
            mv -v "pkgs/${NON_REDIST}" "pkgs/${NON_REDIST}-disabled"
            mv -v pkgs/${NON_REDIST}-ci pkgs/${NON_REDIST}
          fi
        done
        nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L

  build-home:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        home:
          - martin@revan
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.home }} 🏠
      run: |
        # Disable non-redist packages
        for NON_REDIST in cider pico8; do
          if [ -d "pkgs/${NON_REDIST}" ]; then
            mv -v "pkgs/${NON_REDIST}" "pkgs/${NON_REDIST}-disabled"
            mv -v pkgs/${NON_REDIST}-ci pkgs/${NON_REDIST}
          fi
        done
        nix build '.#homeConfigurations."${{ matrix.home }}".activationPackage' -L
