name: Build 🏗️ Workstations ️️🖥️
on:
  push:
    branches:
      - main
    paths:
      - 'flake.lock'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-workstation:
    name: 🖥️
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - '.#nixosConfigurations.phasma.config.system.build.toplevel'
          - '.#homeConfigurations."martin@phasma".activationPackage'
          - '.#nixosConfigurations.vader.config.system.build.toplevel'
          - '.#homeConfigurations."martin@vader".activationPackage'
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@main
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: ${{ matrix.config }}
      run: |
        mv -v "pkgs/pico8" "pkgs/pico8-disabled"
        mv -v pkgs/pico8-ci pkgs/pico8
        sed -i 's|"phasma"|#"phasma"|' nixos/_mixins/desktop/apps/video-production/default.nix
        sed -i 's|"vader"|#"vader"|' nixos/_mixins/desktop/apps/video-production/default.nix
        nix build ${{ matrix.config }} -L