name: Build 🏗️ VMs 👻
on:
  push:
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vm:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        host:
          - crawler
    # Only run this job when the workflow is triggered by a tag
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.host }} ️🧟
      run: |
        nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L

  build-home:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        home:
          - martin@crawler
    # Only run this job when the workflow is triggered by a tag
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.home }} 🏚️
      run: |
        nix build '.#homeConfigurations."${{ matrix.home }}".activationPackage' -L
