name: Build 🏗️ Workstations ️️🖥️
on:
  push:
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-host:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - vader
          - phasma
          - tanis
          - shaa
          - atrius
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@main
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.host }} 🐧
      run: |
        # Disable non-redist packages
        for NON_REDIST in cider pico8; do
          if [ -d "pkgs/${NON_REDIST}" ]; then
            mv -v "pkgs/${NON_REDIST}" "pkgs/${NON_REDIST}-disabled"
            mv -v pkgs/${NON_REDIST}-ci pkgs/${NON_REDIST}
          fi
        done
        nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
        sudo df -h

  build-home:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        home:
          - martin@vader
          - martin@phasma
          - martin@tanis
          - martin@shaa
          - martin@atrius
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@main
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.home }} 🏠
      run: |
        # Disable non-redist packages
        for NON_REDIST in cider pico8; do
          if [ -d "pkgs/${NON_REDIST}" ]; then
            mv -v "pkgs/${NON_REDIST}" "pkgs/${NON_REDIST}-disabled"
            mv -v pkgs/${NON_REDIST}-ci pkgs/${NON_REDIST}
          fi
        done
        nix build '.#homeConfigurations."${{ matrix.home }}".activationPackage' -L
        sudo df -h