name: Build 🏗️ Workstations ️️🖥️
on:
  push:
    branches:
      - main
    paths:
      - 'flake.lock'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-workstation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - '.#nixosConfigurations.phasma.config.system.build.toplevel'
          - '.#homeConfigurations."martin@phasma".activationPackage'
          - '.#nixosConfigurations.vader.config.system.build.toplevel'
          - '.#homeConfigurations."martin@vader".activationPackage'
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@main
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: Building 👷 ${{ matrix.config }} 🐧
      run: |
        for NON_REDIST in cider pico8; do
          if [ -d "pkgs/${NON_REDIST}" ]; then
            mv -v "pkgs/${NON_REDIST}" "pkgs/${NON_REDIST}-disabled"
            mv -v pkgs/${NON_REDIST}-ci pkgs/${NON_REDIST}
          fi
        done
        sed -i 's|"phasma"|#"phasma"|' nixos/_mixins/desktop/apps/video-production/default.nix
        sed -i 's|"vader"|#"vader"|' nixos/_mixins/desktop/apps/video-production/default.nix
        nix build ${{ matrix.config }} -L
        sudo df -h