name: Build 🏗️ Packages ️📦

on:
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'lib/**'
      - 'pkgs/**'
      - 'overlays/**'
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'lib/**'
      - 'pkgs/**'
      - 'overlays/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-apps:
    name: Build 🐧 apps 📦
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - '.#bzmenu.packages.x86_64-linux.default'
          - '.#iwmenu.packages.x86_64-linux.default'
          - '.#nixosConfigurations.vader.pkgs.caddy'
          - '.#nixosConfigurations.vader.pkgs.defold'
          - '.#nixosConfigurations.vader.pkgs.gitkraken'
          - '.#nixosConfigurations.vader.pkgs.gotosocial'
          - '.#nixosConfigurations.vader.pkgs.heynote'
          - '.#nixosConfigurations.vader.pkgs.hyprpicker'
          - '.#nixosConfigurations.vader.pkgs.linuxPackages.mwprocapture'
          - '.#nixosConfigurations.vader.pkgs.ollama'
          - '.#nixosConfigurations.vader.pkgs.open-webui'
          - '.#nixosConfigurations.vader.pkgs.owncast'
          - '.#nixosConfigurations.vader.pkgs.podman-desktop'
          - '.#nixosConfigurations.vader.pkgs.station'
          - '.#nixosConfigurations.vader.pkgs.wavebox'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: Building ${{ matrix.package }} 📦
        continue-on-error: true
        run: |
          nix build ${{ matrix.package }} -L

  build-large-linux-apps:
    name: Build large applications 🎒
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - '.#nixosConfigurations.vader.pkgs.davinci-resolve'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: Building ${{ matrix.package }} 🎒
        continue-on-error: true
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          if ! nix eval ".#${{ matrix.package }}.meta.license.spdxId" --raw 2>/dev/null; then
            nix build ${{ matrix.package }} -L --impure
          else
            nix build ${{ matrix.package }} -L
          fi

  build-darwin-apps:
    name: Build 🍏 apps 📦
    runs-on: macos-latest
    strategy:
      matrix:
        package:
          - '.#darwinConfigurations.momin.pkgs.gitkraken'
          - '.#darwinConfigurations.momin.pkgs.podman-desktop'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: Building ${{ matrix.package }} 📦
        continue-on-error: true
        run: |
          nix build ${{ matrix.package }} -L

  build-fonts:
    name: Build fonts 🔤
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - nerd-font-patcher
          - bebas-neue-2014-font
          - bebas-neue-2018-font
          - bebas-neue-pro-font
          - bebas-neue-rounded-font
          - bebas-neue-semi-rounded-font
          - boycott-font
          - commodore-64-pixelized-font
          - digital-7-font
          - dirty-ego-font
          - fixedsys-core-font
          - fixedsys-excelsior-font
          - impact-label-font
          - mocha-mattari-font
          - poppins-font
          - spaceport-2006-font
          - zx-spectrum-7-font
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: Building ${{ matrix.package }} 🔤
        continue-on-error: true
        run: |
          nix build .#nixosConfigurations.vader.pkgs.${{ matrix.package }} -L

  build-obs-plugins:
    name: Build OBS Plugins 🔌
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - obs-aitum-multistream
          - obs-advanced-masks
          - obs-browser-transition
          - obs-dir-watch-media
          - obs-dvd-screensaver
          - obs-freeze-filter
          - obs-markdown
          - obs-media-controls
          - obs-mute-filter
          - obs-noise
          - obs-recursion-effect
          - obs-replay-source
          - obs-retro-effects
          - obs-rgb-levels
          - obs-scale-to-sound
          - obs-scene-as-transition
          - obs-source-clone
          - obs-stroke-glow-shadow
          - obs-transition-table
          - obs-urlsource
          - obs-vertical-canvas
          - obs-vnc
          - obs-webkitgtk
          - pixel-art
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: Building ${{ matrix.package }} 🔌
        continue-on-error: true
        run: |
          nix build .#nixosConfigurations.vader.pkgs.${{ matrix.package }} -L