name: Build 🏗️ VMs 👻

on:
  push:
    branches:
      - main
    paths:
      - 'flake.lock'
  workflow_dispatch:

jobs:
  build-vm:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        host:
          - crawler
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@main
    - name: Building 👷 ${{ matrix.host }} ️🧟
      run: |
        nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L

  build-home:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        home:
          - martin@crawler
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@main
    - name: Building 👷 ${{ matrix.home }} 🏚️
      run: |
        nix build '.#homeConfigurations."${{ matrix.home }}".activationPackage' -L
