name: Build 🏗️ Packages ️📦

on:
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'lib/**'
      - 'pkgs/**'
      - 'overlays/**'
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'lib/**'
      - 'pkgs/**'
      - 'overlays/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-apps:
    name: 🐧
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - '.#bzmenu.packages.x86_64-linux.default'
          - '.#iwmenu.packages.x86_64-linux.default'
          - '.#nixosConfigurations.vader.pkgs.caddy'
          - '.#cider'
          - '.#defold'
          - '.#nixosConfigurations.vader.pkgs.gitkraken'
          - '.#gotosocial'
          - '.#heynote'
          - '.#hyprpicker'
          - '.#nixosConfigurations.vader.pkgs.linuxPackages.mwprocapture'
          - '.#ollama'
          - '.#open-webui'
          - '.#owncast'
          - '.#podman-desktop'
          - '.#station'
          - '.#nixosConfigurations.vader.pkgs.wavebox'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: ${{ matrix.package }}
        run: |
          nix build ${{ matrix.package }} -L

  build-darwin-apps:
    name: 🍏
    runs-on: macos-latest
    strategy:
      matrix:
        package:
          - '.#darwinConfigurations.momin.pkgs.gitkraken'
          - '.#darwinConfigurations.momin.pkgs.podman-desktop'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: ${{ matrix.package }}
        run: |
          nix build ${{ matrix.package }} -L

  build-fonts:
    name: 🔤
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - '.#nerd-font-patcher'
          - '.#bebas-neue-2014-font'
          - '.#bebas-neue-2018-font'
          - '.#bebas-neue-pro-font'
          - '.#bebas-neue-rounded-font'
          - '.#bebas-neue-semi-rounded-font'
          - '.#boycott-font'
          - '.#commodore-64-pixelized-font'
          - '.#digital-7-font'
          - '.#dirty-ego-font'
          - '.#fixedsys-core-font'
          - '.#fixedsys-excelsior-font'
          - '.#impact-label-font'
          - '.#mocha-mattari-font'
          - '.#poppins-font'
          - '.#spaceport-2006-font'
          - '.#zx-spectrum-7-font'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: ${{ matrix.package }}
        run: |
          nix build ${{ matrix.package }} -L

  build-obs-plugins:
    name: 🔌
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - '.#obs-aitum-multistream'
          - '.#obs-advanced-masks'
          - '.#obs-browser-transition'
          - '.#obs-dir-watch-media'
          - '.#obs-dvd-screensaver'
          - '.#obs-freeze-filter'
          - '.#obs-markdown'
          - '.#obs-media-controls'
          - '.#obs-mute-filter'
          - '.#obs-noise'
          - '.#obs-recursion-effect'
          - '.#obs-replay-source'
          - '.#obs-retro-effects'
          - '.#obs-rgb-levels'
          - '.#obs-scale-to-sound'
          - '.#obs-scene-as-transition'
          - '.#obs-source-clone'
          - '.#obs-stroke-glow-shadow'
          - '.#obs-transition-table'
          - '.#obs-urlsource'
          - '.#obs-vertical-canvas'
          - '.#obs-vnc'
          - '.#obs-webkitgtk'
          - '.#pixel-art'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - name: ${{ matrix.package }}
        run: |
          nix build ${{ matrix.package }} -L