name: Build 🏗️ VMs 👻
on:
  push:
    branches:
      - main
    paths:
      - 'flake.lock'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vm:
    name: 👻
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - '.#nixosConfigurations.crawler.config.system.build.toplevel'
          - '.#homeConfigurations."martin@crawler".activationPackage'
          - '.#nixosConfigurations.dagger.config.system.build.toplevel'
          - '.#homeConfigurations."martin@dagger".activationPackage'
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@main
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - name: ${{ matrix.config }}
      run: |
        mv -v "pkgs/pico8" "pkgs/pico8-disabled"
        mv -v pkgs/pico8-ci pkgs/pico8
        nix build ${{ matrix.config }}