name: Flake ❄️ Publish 📤
on:
  push:
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-flakehub:
    name: Publish Flake ❄️
    runs-on: ubuntu-22.04
    # Only run this job when the workflow is triggered by a tag
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@v1
      - uses: DeterminateSystems/flakehub-push@v5
        with:
          tag: ${{ github.ref }}
          include-output-paths: true
          visibility: "public"
