name: Build 🏗️ and Cache ❄️
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full

jobs:
  DeterminateCI:
    name: Determinate CI 👷
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "read"
    with:
      visibility: true
